syntax = "proto3";

package auth.v1;

option java_package = "com.taxi.microservices.contracts.auth.v1";
option java_multiple_files = true;

import "google/protobuf/empty.proto";


service AuthService {
  rpc CreateDraftPhoneCredential(CreateDraftPhoneCredentialRequest)
      returns (google.protobuf.Empty);

  rpc CreateDraftEmailCredential(CreateDraftEmailCredentialRequest)
      returns (google.protobuf.Empty);

  rpc DeleteDraftCredential(DeleteDraftCredentialRequest)
      returns (google.protobuf.Empty);

  rpc GenerateOtp(GenerateOtpRequest)
      returns (google.protobuf.Empty);

  rpc ConfirmOtp(ConfirmOtpRequest)
      returns (google.protobuf.Empty);
}

message CreateDraftPhoneCredentialRequest {
  string user_id = 1;
  string phone_number = 2;
}

message CreateDraftEmailCredentialRequest {
  string user_id = 1;
  string email = 2;
}

message DeleteDraftCredentialRequest {
  string credential_id = 1;
}

message GenerateOtpRequest {
  string credential_id = 1;
}

message ConfirmOtpRequest {
  string credential_id = 1;
  string otp = 2;
}